[project]
name = "ww-flash-sims"
version = "0.1.0"
description = "python utility library for working with flash simulations"
readme = "README.md"
authors = [
  { name = "Neco Kriel", email = "necokriel@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
sources = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src/ww_flash_sims"]

[tool.pyright]
include = ["src"]
